- name: to test the conditions
  hosts: local
  connection: local
  vars:
    number1: 15

  tasks:
  - name: print if the number is greater than 10
    ansible.builtin.debug:
      msg: "the given number is more than {{number1}}"
    when: number1 > 10 
  - name: print if the number is less  than or equals to 10
    ansible.builtin.debug:
      msg: "the given number is less than or equal to {{number1}}"
    when: number1 <= 10  